kind: Deployment
apiVersion: apps/v1
metadata:
# Set your lab user name
  name: riko2001-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
# Set your lab user name
      app: riko2001-hello-world
  template:
    metadata:
      labels:
# Set your lab user name
        app: riko2001-hello-world
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: 'quay.io/riko2001/my_image:v2'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10